### ISSUE TITLE
Mongo dependency break on Meteor 3 rc.2

### ISSUE THREAD

**Issue by carlosalvidrez** [jankapunkt/meteor-migration-helper#1]
Getting this error, on rc2: 

`   While selecting package versions:
   error: Conflict: Constraint mongo@1.10.1 || 1.12.0 is not satisfied by mongo
   2.0.0-rc300.2.
   Constraints on package "mongo":
   * mongo@2.0.0-rc300.2 <- top level
   * mongo@~2.0.0-rc300.2 <- top level
   * mongo@2.0.0-rc300.2 <- reactive-dict 1.3.2-rc300.2
   * mongo@2.0.0-rc300.2 <- service-configuration 1.3.2-rc300.2
   * mongo@2.0.0-rc300.2 <- accounts-base 3.0.0-rc300.2
   * mongo@1.10.1 || 1.12.0 <- jkuester:migration-helper 1.0.2`

**Comment by jankapunkt** [comment]
Thank you for the hint, please update to `jkuester:migration-helper@1.1.0` and let me know if it works or not.

**Comment by carlosalvidrez** [comment]
That worked, thank you!
